import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';

const inter = Rubik({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <meta charSet='UTF-8' />
      <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
